server:
  tomcat:
    #强制项目还是用utf-8编码
    uri-encoding: UTF-8

    #自带tomcat设置参数
    max-connections: 20
    threads:
      max: 20
      min-spare: 20 #Minimum amount of worker threads.
    max-http-form-post-size: 500MB #Maximum size of the form content in any HTTP post request.

  port: 80

  #强制项目还是用utf-8编码
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  #强制项目还是用utf-8编码
  messages:
    encoding: UTF-8
  banner:
    charset: UTF-8
    location: banner.txt

# 集成arthas
arthas:
  #连接时使用-agentId
  agent-id: xxxx
  # arthas-tunnel-server-3.5.1-fatjar.jar 启动后 根据ip + 端口 + agent-id
  tunnel-server: ws://127.0.0.1:7777/ws
